export {
  saveProgress,
  loadProgress,
  clearProgress,
  hasSaveData,
  getSaveInfo,
  getSaveVersion,
  getStorageSize,
  getRawSaveData,
  decodeOptimizedProgress,
  convertToGameStateFormat,
  isOptimizedFormat,
  cleanupLegacyKeys,
  saveAudioSettings,
  loadAudioSettings,
  clearAudioSettings,
  type LoadResult,
  type OptimizedProgress,
  type OptimizedCurrentState,
  type OptimizedSelectionState,
  type DecodedBookProgress,
  type DecodedProgress,
} from './saveSystem';
