/**
 * Character information panel component
 */

'use client';

import type { Character } from '@/lib/dialogue/types';
import type { ValidationResult } from '../types/creator.types';
import TagInput from './TagInput';
import { generateCharacterIdFromName, isAutoGeneratedId } from '../utils/idGenerator';
import styles from '../styles/dialogue-creator.module.css';

const LOADING_GROUPS = [
  { value: 'introduction_characters', label: 'Introduction Characters' },
  { value: 'regular_contacts', label: 'Regular Contacts' },
  { value: 'essential_library_staff', label: 'Essential Library Staff' },
  { value: 'extended_library_staff', label: 'Extended Library Staff' },
  { value: 'long_term_scholars', label: 'Long-term Scholars' },
  { value: 'visiting_scholars', label: 'Visiting Scholars' },
  { value: 'visiting_dignitaries', label: 'Visiting Dignitaries' },
  { value: 'knowledge_contributors', label: 'Knowledge Contributors' },
  { value: 'special_event_characters', label: 'Special Event Characters' },
];

const RETIRE_OPTIONS = [
  { value: 'never', label: 'Never' },
  { value: 'hook', label: 'Hook' },
  { value: 'first_plot_point', label: 'First Plot Point' },
  { value: 'first_pinch_point', label: 'First Pinch Point' },
  { value: 'midpoint', label: 'Midpoint' },
  { value: 'second_pinch_point', label: 'Second Pinch Point' },
  { value: 'second_plot_point', label: 'Second Plot Point' },
  { value: 'climax', label: 'Climax' },
  { value: 'resolution', label: 'Resolution' },
];

interface CharacterInfoPanelProps {
  character: Character;
  onChange: (field: keyof Character, value: any) => void;
  errors: ValidationResult[];
}

export default function CharacterInfoPanel({
  character,
  onChange,
  errors,
}: CharacterInfoPanelProps) {
  const getError = (field: string) =>
    errors.find((e) => e.field === `character.${field}`)?.message;

  const handleNameChange = (name: string) => {
    onChange('name', name);
    // Auto-generate ID if it hasn't been manually edited
    if (!character.id || isAutoGeneratedId(character.id, character.name)) {
      const autoId = generateCharacterIdFromName(name);
      onChange('id', autoId);
    }
  };

  return (
    <section className={styles.panel}>
      <h2 className={styles.panelTitle}>Character Information</h2>

      <div className={styles.formGroup}>
        <label htmlFor="char-id">
          Character ID <span className={styles.required}>*</span>
        </label>
        <input
          id="char-id"
          type="text"
          value={character.id}
          onChange={(e) => onChange('id', e.target.value)}
          className={getError('id') ? styles.inputError : styles.input}
          placeholder="character-id-example"
        />
        {getError('id') && (
          <span className={styles.errorMessage}>{getError('id')}</span>
        )}
        <span className={styles.helperText}>
          Lowercase letters, numbers, and hyphens only
        </span>
      </div>

      <div className={styles.formGroup}>
        <label htmlFor="char-name">
          Character Name <span className={styles.required}>*</span>
        </label>
        <input
          id="char-name"
          type="text"
          value={character.name}
          onChange={(e) => handleNameChange(e.target.value)}
          className={getError('name') ? styles.inputError : styles.input}
          placeholder="Character Name"
        />
        {getError('name') && (
          <span className={styles.errorMessage}>{getError('name')}</span>
        )}
      </div>

      <div className={styles.formGroup}>
        <label htmlFor="char-title">
          Title <span className={styles.required}>*</span>
        </label>
        <input
          id="char-title"
          type="text"
          value={character.title}
          onChange={(e) => onChange('title', e.target.value)}
          className={getError('title') ? styles.inputError : styles.input}
          placeholder="Character Title or Role"
          maxLength={100}
        />
        <span className={styles.charCount}>
          {character.title.length}/100
        </span>
        {getError('title') && (
          <span className={styles.errorMessage}>{getError('title')}</span>
        )}
      </div>

      <div className={styles.formGroup}>
        <label htmlFor="char-description">
          Description <span className={styles.required}>*</span>
        </label>
        <textarea
          id="char-description"
          value={character.description}
          onChange={(e) => onChange('description', e.target.value)}
          className={getError('description') ? styles.inputError : styles.textarea}
          placeholder="Describe the character's personality, role, and background..."
          rows={4}
          maxLength={500}
        />
        <span className={styles.charCount}>
          {character.description.length}/500
        </span>
        {getError('description') && (
          <span className={styles.errorMessage}>{getError('description')}</span>
        )}
      </div>

      <div className={styles.formGroup}>
        <label htmlFor="char-portrait">
          Portrait File <span className={styles.required}>*</span>
        </label>
        <input
          id="char-portrait"
          type="text"
          value={character.portraitFile}
          onChange={(e) => onChange('portraitFile', e.target.value)}
          className={getError('portraitFile') ? styles.inputError : styles.input}
          placeholder="character-portrait.svg"
        />
        {getError('portraitFile') && (
          <span className={styles.errorMessage}>{getError('portraitFile')}</span>
        )}
        <span className={styles.helperText}>
          Filename of the character portrait image
        </span>
      </div>

      <div className={styles.formGroup}>
        <label htmlFor="char-loading-group">
          Loading Group <span className={styles.required}>*</span>
        </label>
        <select
          id="char-loading-group"
          value={character.loadingGroup}
          onChange={(e) => onChange('loadingGroup', e.target.value)}
          className={getError('loadingGroup') ? `${styles.select} ${styles.inputError}` : styles.select}
        >
          {LOADING_GROUPS.map((group) => (
            <option key={group.value} value={group.value}>
              {group.label}
            </option>
          ))}
        </select>
        {getError('loadingGroup') && (
          <span className={styles.errorMessage}>{getError('loadingGroup')}</span>
        )}
        <span className={styles.helperText}>
          Determines when character is loaded during gameplay
        </span>
      </div>

      <div className={styles.formGroup}>
        <label htmlFor="char-retire">
          Retire After <span className={styles.required}>*</span>
        </label>
        <select
          id="char-retire"
          value={character.retireAfter}
          onChange={(e) => onChange('retireAfter', e.target.value)}
          className={getError('retireAfter') ? `${styles.select} ${styles.inputError}` : styles.select}
        >
          {RETIRE_OPTIONS.map((option) => (
            <option key={option.value} value={option.value}>
              {option.label}
            </option>
          ))}
        </select>
        {getError('retireAfter') && (
          <span className={styles.errorMessage}>{getError('retireAfter')}</span>
        )}
        <span className={styles.helperText}>
          Character stops appearing after this story beat
        </span>
      </div>

      <div className={styles.formGroup}>
        <label>Specialties</label>
        <TagInput
          tags={character.specialties}
          onChange={(tags) => onChange('specialties', tags)}
          placeholder="Add specialty..."
        />
        <span className={styles.helperText}>
          Character expertise areas (e.g., interdimensional_cataloging)
        </span>
      </div>
    </section>
  );
}

