/**
 * ID generation utilities for character and dialogue IDs
 */

/**
 * Generate character ID from character name
 */
export function generateCharacterIdFromName(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '') // Remove special chars
    .replace(/\s+/g, '-')          // Replace spaces with hyphens
    .replace(/-+/g, '-')           // Collapse multiple hyphens
    .replace(/^-|-$/g, '');        // Remove leading/trailing hyphens
}

/**
 * Generate dialogue ID from category and existing IDs
 */
export function generateDialogueId(
  category: string,
  existingIds: string[]
): string {
  // Extract first word of category
  const categoryWord = category.split('-')[0];

  // Common second words for natural IDs
  const secondWords = [
    'general', 'specific', 'first', 'second', 'warm',
    'casual', 'formal', 'intro', 'outro', 'progress',
    'start', 'mid', 'end', 'early', 'late'
  ];

  // Try to generate unique ID
  let baseId = categoryWord;
  let counter = 1;

  // First try with second word
  for (const word of secondWords) {
    const candidateId = `${word}-${baseId}`;
    if (!existingIds.includes(candidateId)) {
      return candidateId;
    }
  }

  // Fall back to numbered IDs
  while (existingIds.includes(`${baseId}-${counter}`)) {
    counter++;
  }

  return `${baseId}-${counter}`;
}

/**
 * Check if ID was auto-generated (to know if we should update it)
 */
export function isAutoGeneratedId(
  currentId: string,
  name: string
): boolean {
  const expectedId = generateCharacterIdFromName(name);
  return currentId === expectedId;
}

